# Generated by Django 4.0.3 on 2022-04-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('device', models.TextField(blank=True, null=True)),
                ('datecreated', models.TextField(blank=True, db_column='dateCreated', null=True)),
            ],
            options={
                'db_table': 'Download',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('party_id', models.IntegerField(blank=True, null=True)),
                ('difficulty', models.IntegerField(blank=True, null=True)),
                ('played_audio', models.IntegerField(blank=True, null=True)),
                ('final_time', models.IntegerField(blank=True, null=True)),
                ('penalties', models.IntegerField(blank=True, null=True)),
                ('datecreated', models.TextField(blank=True, db_column='dateCreated', null=True)),
            ],
            options={
                'db_table': 'Levels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('session_id', models.IntegerField(blank=True, null=True)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('time_played', models.IntegerField(blank=True, null=True)),
                ('datecreated', models.TextField(blank=True, db_column='dateCreated', null=True)),
            ],
            options={
                'db_table': 'Party',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('time_played', models.IntegerField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('datecreated', models.TextField(blank=True, db_column='dateCreated', null=True)),
            ],
            options={
                'db_table': 'Session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ip', models.TextField(blank=True, null=True)),
                ('device', models.TextField(blank=True, null=True)),
                ('datecreated', models.TextField(blank=True, db_column='dateCreated', null=True)),
            ],
            options={
                'db_table': 'Visit',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='countries',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
