# Generated by Django 4.0.3 on 2022-04-23 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_customuser_country'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
