# Generated by Django 4.0.3 on 2022-04-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_user_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levels',
            name='played_audio',
        ),
        migrations.RemoveField(
            model_name='party',
            name='time_played',
        ),
    ]
